version: '3'
services:
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin:4.8.1"
        container_name: "phpmyadmin"
        ports:
            - "9090:80"
        environment:
            - PMA_ARBITRARY=1         
    db:
        image: "mysql:5.7"
        container_name: "phpmyadmin_db"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
